### ISSUE TITLE
Unnecessary conditional checks

### ISSUE THREAD

**Issue by RA80533** [UJGA/MWRandomClassGenerator#11]
Starting on [line 658](https://github.com/RA80533/MWRandomClassGenerator/blob/352a27a111a501127eb8448114a1523cc0cf41d7/scripts.js#L658) of [scripts.js](https://github.com/RA80533/MWRandomClassGenerator/blob/352a27a111a501127eb8448114a1523cc0cf41d7/scripts.js), generated weapons are passed through a long line of conditional statements. While the logic performed by each conditional statement is redundant to begin with, the statements themselves will *all* be checked.

There are two possible solutions for this sort of issue: 1) use if-else statements instead of multiple if statements or 2) use a switch statement. Switch statements are very effective in dealing with multiple permutations of the same sort of conditional statement and using one would, therefore, be a perfect solution to the unnecessary conditional checks.

```javascript
switch (randomPrimary.name) {
  case "M4A1":
    // TODO Call the function for the M4A1
    break;
  case "Kilo 141":
    // TODO Call the function for the Kilo 141
    break;
}
```

**Comment by DrFizzles** [comment]
You could also just put all of the weapon names/functions in an object and call them dynamically like this:

```
var primaries = {
  "M4A1": m4a1,
  "Kilo 141": kilo141
}

primaries[randomPrimary.name]();
```

This way you aren't iterating over anything, and instead just calling the needed function.
