### ISSUE TITLE
IDEA - Have a checklist to exclude weapons or attachments 

### ISSUE THREAD

**Issue by fuffingtonsmythe** [UJGA/MWRandomClassGenerator#13]
It could be beneficial to have an option where you can select or deselect certain weapons or attachments. For example if you wanted to limit yourself to AR's or if you didn't have a number of attachments you could generate classes that are relevant.

**Comment by Stortex** [comment]
I think same for perks would be usefull as well

**Comment by PresWiFi** [comment]
This defeats the purpose of "random"
