### ISSUE TITLE
Add overkill

### ISSUE THREAD

**Issue by xXFitzXx** [UJGA/MWRandomClassGenerator#14]
when will overkill comeback, and also it seems that i get a lot of the same 4 guns. (pkm, r9-0, origin 12, and riot shield ) could you please fix this>

**Comment by UJGA** [comment]
1. Because people keep submitting bug reports for it, never. 

2. Every gun has the same chance of being generated. There is nothing to fix.

**Comment by xXFitzXx** [comment]
oh.

**Comment by xXFitzXx** [comment]
sory
