### ISSUE TITLE
Needs update for generator cw guns missing

### ISSUE THREAD

**Issue by joshw007** [UJGA/MWRandomClassGenerator#21]
Plz add cold war guns to the class generator please

**Is your feature request related to a problem? Please describe.**

Guns from cold war are missing in generator

**Describe the solution you'd like**

I want combination of mw and cw guns in class generator please

**Describe alternatives you've considered**

**Additional context**

**Comment by PresWiFi** [comment]
Literally the first thing listed on the website is the link to the Cold War generator. 

https://coldwarrandomclass.com/

**Comment by PresWiFi** [comment]
There will not be a generator combining them.
